# Generated by Django 2.2 on 2025-10-25 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('BAR', 'Bar / Pub'), ('TRIVIA', 'Trivia / Pub Quiz'), ('KARAOKE', 'Karaoke'), ('LIVE_MUSIC', 'Live Music'), ('ACTIVITY', 'Activity (pool, darts, bowling, etc.)'), ('CLUB', 'Club'), ('FOOD', 'Food / Restaurant'), ('OTHER', 'Other')], default=('OTHER', 'Other'), max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(default='Glasgow', max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('longitude', models.IntegerField(blank=True)),
                ('latitude', models.IntegerField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('best_days', multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=20)),
                ('tags', models.ManyToManyField(blank=True, related_name='venues', to='planner.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget', models.CharField(choices=[('LOW', '£'), ('MEDIUM', '££'), ('HIGH', '£££')], default=('MEDIUM', '££'), max_length=10)),
                ('min_group_size', models.PositiveIntegerField(default=2)),
                ('max_group_size', models.PositiveIntegerField(blank=True, help_text='Null = no hard limit', null=True)),
                ('booking_url', models.URLField(blank=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='planner.Tag')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.Venue')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city', 'is_active'], name='planner_ven_city_f8377d_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['kind'], name='planner_ven_kind_90dc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='planner_ven_name_6063cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'address')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['budget'], name='planner_eve_budget_fcd193_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='planner_eve_is_acti_0a4007_idx'),
        ),
    ]
