# Generated by Django 2.2 on 2025-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='budget',
            field=models.CharField(choices=[('LOW', '£'), ('MEDIUM', '££'), ('HIGH', '£££')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='venue',
            name='kind',
            field=models.CharField(choices=[('BAR', 'Bar / Pub'), ('TRIVIA', 'Trivia / Pub Quiz'), ('KARAOKE', 'Karaoke'), ('LIVE_MUSIC', 'Live Music'), ('ACTIVITY', 'Activity (pool, darts, bowling, etc.)'), ('CLUB', 'Club'), ('FOOD', 'Food / Restaurant'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
