# Generated by Django 2.2 on 2025-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20251025_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='eastings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='northings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'postcode')},
        ),
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='longitude',
        ),
    ]
