# Generated by Django 2.2 on 2025-10-25 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20251025_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rating_count',
        ),
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
