# Generated by Django 2.2 on 2025-10-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20251025_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='booking_url',
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
